steps:
  - id: "set build number from git push"
    name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git rev-parse --short HEAD > _BUILDNUMBER
    waitFor: ['-']

  - id: "build and deploy a dataflow job"
    name: 'maven:3.6.0-jdk-11-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        buildNumber=$(cat _BUILDNUMBER)
        echo "Build Number is ${buildNumber}"
        apt-get update
        apt-get install sudo
        sudo bash submit.sh com.blizzard.demo.DataflowPipeline \
          --project=blz-d-gdp-telemetry\
          --stagingLocation=gs://gcp-dataflow-cloudbuild-stage/staging/ \
          --gcpTempLocation=gs://gcp-dataflow-cloudbuild-temp/temp/ \
          --runner=DataflowRunner \
          --buildNumber=${buildNumber} \
          --inputTopic=cloudbuild-dataflow \
          --outputTopic=cloudbuild-dataflow-1 \
          --serviceAccount=dataflow-sa@blz-d-gdp-telemetry.iam.gserviceaccount.com \
          --jobName=cloudbuild-dataflowjob-1 \
          --numWorkers=2  \
          --maxNumWorkers=20  \
          --usePublicIps=false \
          --subnetwork=https://www.googleapis.com/compute/v1/projects/blz-cf-xpn-dev-709e47/regions/us-west2/subnetworks/blz-d-gdp-telemetry-usw2-pri \
          --region=us-west2
    waitFor: ['set build number from git push']
  
  