steps:
  - id: "set build number"
    name: gcr.io/cloud-builders/git
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git rev-parse --short HEAD > _BUILDNUMBER
    waitFor: ['-']

  - id: "build and deploy a dataflow job"
    name: maven:3.6.0-jdk-11-slim
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        buildNumber=$(cat _BUILDNUMBER)
        export PROJECT_NAME=$(gcloud config get-value project)
        echo "Build Number is ${buildNumber}"
        apt-get update
        apt-get install sudo
        sudo bash submit.sh com.blizzard.demo.DataflowPipeline \
          --project= $PROJECT_NAME \
          --stagingLocation=gs://$PROJECT_NAME/gcp-dataflow-cloudbuild-stage/ \
          --gcpTempLocation=gs://$PROJECT_NAME/gcp-dataflow-cloudbuild-temp/ \
          --runner=DataflowRunner \
          --autoscalingAlgorithm=THROUGHPUT_BASED \
          --buildNumber=${buildNumber} \
          --inputTopic=perryTest
          --outputTopic=perryTest-1
          --region=us-west1
    waitFor: ['set build number']
  
  